services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      target: workspace
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    init: true
    tty: true # for devcontainer

volumes:
  node_modules:
