# yaml-language-server: $schema=https://json.schemastore.org/taskfile
# cSpell:ignore esbuild, outfile
---
version: '3'

tasks:
  build:
    cmds:
      # SEE: https://github.com/evanw/esbuild/issues/1921#issuecomment-1720348876
      - npx esbuild src/cli.mts --outfile=dist/cli.mjs --platform=node --format=esm --bundle --banner:js='const require = (await import("node:module")).createRequire(import.meta.url)'
      - chmod +x dist/cli.mjs

  lint:
    deps:
      - lint:tsc
      - lint:prettier
      - lint:eslint

  lint:tsc: npx tsc --noEmit

  lint:prettier: npx prettier --check .

  lint:eslint: npx eslint --ext ts,mts .

  test: npx vitest

  tag:patch:
    cmd:
      task: tag:internal
      vars: { VERSION: 'patch' }

  tag:minor:
    cmd:
      task: tag:internal
      vars: { VERSION: 'minor' }

  tag:major:
    cmd:
      task: tag:internal
      vars: { VERSION: 'major' }

  tag:internal:
    internal: true
    label: 'tag:internal:{{.VERSION}}'
    preconditions:
      - git diff --quiet --exit-code && git diff --quiet --exit-code --cached
    cmds:
      - 'npm version {{.VERSION}} -m ":bookmark: v%s"'

  publish:
    deps:
      - build
    preconditions:
      - npx can-npm-publish
    cmd: npm publish

  clean: rm -rf dist
