# yaml-language-server: $schema=https://json.schemastore.org/taskfile
# cSpell:ignore esbuild, outfile
---
version: '3'

tasks:
  build:
    cmds:
      - npx esbuild src/cli.mts --outfile=dist/cli.mjs --platform=node --format=esm --bundle --minify
      - chmod +x dist/cli.mjs

  lint:
    deps:
      - lint:tsc
      - lint:prettier
      - lint:eslint

  lint:tsc: npx tsc --noEmit

  lint:prettier: npx prettier --check .

  lint:eslint: npx eslint --ext ts,mts .

  test: npx vitest

  clean: rm -rf dist
