name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: echo "node_version=$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> $GITHUB_OUTPUT
        id: node_version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          cache: npm

      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - run: npm ci

      - run: task lint

      - run: task test

      - run: task build
