name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'patch | minor | major'
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - run: echo "node_version=$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> $GITHUB_OUTPUT
        id: node_version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}

      - run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@github.com'
          git checkout -b actions/main/release-${{ github.event.inputs.version }}
          npm version --no-git-tag-version ${{ github.event.inputs.version }}
          git add package.json package-lock.json
          git commit -m ":bookmark: v$(jq -r '.version' package.json)"
          git push -u origin HEAD

      - run: |
          PR_URL=$(gh pr create --base main --head actions/main/release-${{ github.event.inputs.version }} --label Release)
          gh pr merge --auto --merge --delete-branch $PR_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
