name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish_npm:
    name: Publish to npm
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: echo "node_version=$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> $GITHUB_OUTPUT
        id: node_version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - run: npm ci

      - run: task publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
