# cSpell:ignore aquaproj
---
name: Publish

on:
  release:
    types:
      - published

run-name: Publish ${{ github.event.release.tag_name }}

permissions:
  contents: read

jobs:
  publish_npm:
    name: Publish to npm
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute node version
        run: echo "node_version=$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> "$GITHUB_OUTPUT"
        id: node_version

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: task publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
